### ISSUE TITLE
TCP connection termination

### ISSUE THREAD

**Issue by Fritzelblitz** [HCA-Healthcare/elixir-mllp#51]
If a TCP connection opened via MLLP.Client.start_link is closed by the remote side before we could send the message, the message will be sent to the closed connection and we will get the error message that the connection was closed. After that a connection is re-established and after some time it is closed again by the remote side. As far as I understand the connection behavior of the MLLP.client, this behavior is expected.

Would it make sense that MLLP.Client.send always tries to re-establish the connection when trying to send if the connection is not established?

**Comment by Fritzelblitz** [comment]
I tried an explicit call to MLLP.Client.reconnect, but this did not work as expected #52

**Comment by starbelly** [comment]
@Fritzelblitz  do you think you still need the behaviour where by when you send and it's not connected it should attempt to connect?

@vikas15bhardwaj  what do you think about this?

**Comment by Fritzelblitz** [comment]
With the patched reconnect function, I would no longer need the feature.

However, I still think it would be useful, it doesn't seem to make sense to send messages to a closed connection. At least as an option for the MLLP GenServer to reopen the connection on a send when it is closed would make sense.

**Comment by vikas15bhardwaj** [comment]
@starbelly I think it would be OK for send to reconnect if it sees client is not connected anymore. This will avoid apps worrying about reconnection. Do you see any downside with it?

**Comment by starbelly** [comment]
@vikas15bhardwaj  Nah, I don't think so, other than implicit behaviour. I think we should support this.

**Comment by starbelly** [comment]
I think this might be resolved via #68 , @Fritzelblitz  maybe you can try that out before it gets merged?

**Comment by starbelly** [comment]
I'm pretty sure the above mentioned PR which has been merged solves this issue. We will release this after a fair bit of testing. However, going to close this issue, if you feel this doesn't solve the problem, please re-open it.
