### ISSUE TITLE
Bump telemetry dependency version

### ISSUE THREAD

**Issue by jaj42** [HCA-Healthcare/elixir-mllp#57]
Hi,
I'm sorry if this is stupid but I'm just getting started with Elixir.
I'm trying to build an umbrella app with an HL7 listener streaming to a phoenix web app. Unfortunately it seems I cannot mix mllp with phoenix because they depend on different versions of the telemetry package:

```
Because "the lock" specifies telemetry 1.1.0 and every version of mllp depends on telemetry ~> 0.4.3, the lock is incompatible with mllp.
And because your app depends on the lock, no version of mllp is allowed.
So, because your app depends on mllp ~> 0.8, version solving failed.
```

Since telemetry 0.4.3 seems to be very old, I was wondering if the version could be updated in the mllp dependencies.

Regards,
Jona

**Comment by starbelly** [comment]
Closed via #58 

Edit: 

We'll get a release done soon ❤️
