### ISSUE TITLE
MLLP Client raises error when stopped normally

### ISSUE THREAD

**Issue by aggrhm** [HCA-Healthcare/elixir-mllp#59]
Is there a reason why the client logs an error when stopped in the terminate method (https://github.com/HCA-Healthcare/elixir-mllp/blob/main/lib/mllp/client.ex#L454)? 

In our utility we don't need to keep the connection alive after we send messages, so we release the pid by calling `stop`, but it results in an error in the logs with `Reason: :normal`.

**Comment by starbelly** [comment]
Yeah, I think this should be a debug message or configurable. Debug message makes more sense to me though. @vikas15bhardwaj  wdyt?

**Comment by vikas15bhardwaj** [comment]
Can we check for exit reason and log it accordingly. Since it's in terminate callback, you want to log it as error if gneserver terminates unexpectedly otherwise just debug level would be good.

**Comment by starbelly** [comment]
Closed via #60
