### ISSUE TITLE
Dialyzer not happy when `ref:` passed in receiver child_spec

### ISSUE THREAD

**Issue by cdegroot** [HCA-Healthcare/elixir-mllp#75]
I'm new to this library, but noticed that Elixir-LS was not happy with our invocation of `MLLP.Receiver.child_spec/1` - we pass a reference, but the options type does not allow for that. 

Unless I'm missing something, this should be a simple matter of allowing `ref` in `options()`?

**Comment by starbelly** [comment]
> I'm new to this library, but noticed that Elixir-LS was not happy with our invocation of `MLLP.Receiver.child_spec/1` - we pass a reference, but the options type does not allow for that.
> 
> Unless I'm missing something, this should be a simple matter of allowing `ref` in `options()`?


That is 100% correct, a simple PR to add `ref()` to the type `options()` would indeed solve your issue.
